local basalt = require("/lib/basalt")
local tx,ty = term.getSize()
local main = basalt.createFrame()
main:setBackground(colors.white)
local sideBar = main:addList()
sideBar:setSize(15,ty)
sideBar:addItem("System Config")
sideBar:addItem("Start Menu")
sideBar:addItem("Modems")
sideBar:addItem("Monitors")
sideBar:addItem("Speakers")
sideBar:addItem("Printers")
sideBar:addItem("Disk Drives")
sideBar:addItem("Customizaton")
sideBar:addItem("BIOS & Recovery")
sideBar:addItem("Paint")
sideBar:addItem("Edit")
sideBar:addItem("Terminal")
sideBar:addItem("File Maniger")
sideBar:addItem("About")

basalt.autoUpdate()
