--[[> Copyright XenusSoft 2020 <]]--
--[[>  Use of file is allowed. <]]--

parallel.waitForAny(function()
  --< code here >--
  sleep(8) -- remove this, just for show
end, function()
  local title = "Booting Aurora OS..." -- Change title to what you perfer for the bootup.
  w, h = term.getSize()
  wm, hm = w/2, h/2
  term.setBackgroundColor(colors.white)
  term.setTextColor(colors.black)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  sleep(0.1)
  term.setBackgroundColor(colors.lightGray)
  term.setTextColor(colors.gray)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  sleep(0.1)
  term.setBackgroundColor(colors.gray)
  term.setTextColor(colors.lightGray)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  sleep(0.1)
  term.setBackgroundColor(colors.black)
  term.setTextColor(colors.white)
  term.setCursorPos(wm - (#title/2), hm)
  term.clear()
  term.write(title)
  sleep(1)
  while true do
    w, h = term.getSize()
    wm, hm = w/2, h/2
    term.clear()
    for i = 1, 2 do
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.lightGray)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
      sleep(0.025)
      term.clear()
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
      sleep(0.025)
      term.clear()
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.lightGray)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
      sleep(0.025)
      term.clear()
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.white)
      term.setCursorPos(wm - (#title/2), hm)
      term.write(title)
      sleep(0.025)
    end
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.setCursorPos(wm - (#title/2), hm)
    term.clear()
    term.write(title)
    sleep(2)
  end
end)
term.clear()
term.setTextColor(colors.white)
term.setCursorPos(1, 1)
