--local arg = {...}
isFormatDriveChecked = arg[1]
BuildChaneltoInstall = arg[2]
VersionToInstall = arg[3]
version = arg[4]

print("Installing Aurora OS 1.0.0 ALPHA")
shell.run("mkdir /lib/")
shell.run("mkdir /system64/")
shell.run("mkdir /system64/cpl/")
shell.run("mkdir /program_files/")
print("Please Wait...")
sleep(1)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/startup.lua /startup.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/lib/BSOD.lua /lib/BSOD.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/desktop.lua /system64/desktop.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/shell.lua /system64/shell.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/OS_Boot.lua /system64/OS_Boot.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/all_program_list.lua /system64/all_program_list.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/app_launch.lua /system64/app_launch.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/control.lua /system64/control.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/game_list.lua /system64/game_list.lua")
print("Chilling Down for a moment")
sleep(1)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/about.lua /system64/cpl/about.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/biosrecpvery.lua /system64/cpl/biosrecpvery.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/customization.lua /system64/cpl/customization.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/diskdrive.lua /system64/cpl/diskdrive.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/edit.lua /system64/cpl/edit.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/filemaniger.lua /system64/cpl/filemaniger.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/modem.lua /system64/cpl/modem.lua")
print("Chilling Down for a moment")
sleep(1)
shell.run("wget run https://raw.githubusercontent.com/Pyroxenium/Basalt/refs/heads/master/docs/install.lua release latest.lua /lib/basalt.lua")
print("Chilling Down for a moment")
sleep(1)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/paint.lua /system64/cpl/paint.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/printers.lua /system64/cpl/printers.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/speakers.lua /system64/cpl/speakers.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/speakers.lua /system64/cpl/speakers.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/system.lua /system64/cpl/system.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/terminal.lua /system64/cpl/terminal.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/program_files/minex/minexp.lua /program_files/minex/minexp.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/sysrecovery/file_index.json /recovery/file_index.json")
