
print("Installing Aurora OS Terminal Pre Alpha 0.0.1")
shell.run("mkdir /lib/")
shell.run("mkdir /system64/")
shell.run("mkdir /system64/cpl/")
shell.run("mkdir /program_files/")
print("Please Wait...")
sleep(1)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/shell.lua /startup.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/cpl/about.lua /system64/cpl/about.lua")
sleep(0.3)
shell.run("wget https://raw.githubusercontent.com/JV-lab-create/Aurora-OS/refs/heads/main/system64/app_launch.lua /system64/app_launch.lua")
print("Terminal Pre Alpha 0.0.1 is finished installing!")
sleep(1)