print("Installing Games")
shell.run("mkidr /program_files/games/")
shell.run("wget https://raw.githubusercontent.com/cc-tweaked/treasure-disks/refs/heads/master/data/computercraft/lua/treasure/dan200/alongtimeago/alongtimeago.lua /program_files/games/alongtimeago.lua")
shell.run("wget https://raw.githubusercontent.com/cc-tweaked/treasure-disks/refs/heads/master/data/computercraft/lua/treasure/fredthead/protector/protector.lua /program_files/games/protector.lua")
shell.run("https://raw.githubusercontent.com/cc-tweaked/treasure-disks/refs/heads/master/data/computercraft/lua/treasure/gopher_atl/battleship/battleship.lua /program_files/games/battleship.lua")
shell.run("wget https://raw.githubusercontent.com/cc-tweaked/treasure-disks/refs/heads/master/data/computercraft/lua/treasure/gravity_score/luaide/luaide.lua /program_files/games/luaide.lua")
shell.run("wget https://github.com/cc-tweaked/treasure-disks/blob/master/data/computercraft/lua/treasure/jtk/maze3d/maze2d.lua /program_files/games/maze2d.lua")
shell.run("wget https://github.com/cc-tweaked/treasure-disks/blob/master/data/computercraft/lua/treasure/jtk/maze3d/maze3d.lua /program_files/games/maze3d.lua")
shell.run("wget https://raw.githubusercontent.com/cc-tweaked/treasure-disks/refs/heads/master/data/computercraft/lua/treasure/theoriginalbit/tictactoe/tictactoe.lua /program_files/games/ticktactoe.lua")
shell.run("wget https://raw.githubusercontent.com/cc-tweaked/treasure-disks/refs/heads/master/data/computercraft/lua/treasure/vilsol/gameoflife/gameoflife.lua /program_files/games/gameoflife.lua")
